server:
  port: 8080

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sky_take_out?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 050826
  data:
    redis:
      host: 172.30.215.133    # WSL IP，不是 localhost
      port: 6379
      password:                # 没有密码就空着
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

mybatis:
  # mapper 映射文件路径
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    # 开启驼峰命名映射（如 user_name -> userName）
    map-underscore-to-camel-case: true

# PageHelper 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

sky:
  jwt:
    # 管理端员工登录的 JWT 密钥
    admin-secret-key: sky-take-out-admin-secret-key-GM666
    # 令牌过期时间（毫秒），默认 2 小时
    admin-ttl: 720000000
    # 令牌名称
    admin-token-name: token

    user-secret-key: sky-take-out-user-secret-key-GM666
    user-ttl: 720000000
    # 与小程序 utils/request.js 中的请求头保持一致（小程序用 authentication 头携带 token）
    user-token-name: authentication
  # 微信小程序配置
  wechat:
    app-id: wxb0d179c3dee82381
    app-secret: ec860c2714fc0e09ec0ce15e9d623229
    redirect-uri: https://localhost:8080/user/login